services:
  - type: web
    name: ebook-server
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: node dist/index.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        sync: false # lo configurás en el dashboard de Render o lo ponés manual
      - key: PORT
        value: 10000